import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Footer } from "../components/Footer";
import { Main } from "../components/Main";
import { Header } from "../components/Header";
import { useCounter } from "src/hooks/useCounter";
import { useInputArray } from "src/hooks/useInputArray";
import { useBgLightBlue } from "src/hooks/useBgLightBlue";

export default function Home() {
	const { foo, isShow, handleClick, handleDisplay } = useCounter();
	const { text, array, handleChange, handleAdd } = useInputArray();
	useBgLightBlue();

	return (
		<div className={styles.container}>
			<Head>
				<title>Index Page</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />

			{isShow ? <h1>{foo}</h1> : null}
			<button type="button" onClick={handleClick}>
				ボタン
			</button>
			<button type="button" onClick={handleDisplay}>
				{isShow ? "非表示" : "表示"}
			</button>

			<input type="text" name="" value={text} onChange={handleChange} />
			<button onClick={handleAdd}>追加</button>
			<ul>
				{array.map((item) => {
					return <li key={item}>{item}</li>;
				})}
			</ul>
			<Main page="index" />
			<Footer />
		</div>
	);
}
